# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-assets
  
title: Devin De Silva
email: devin.18@cse.mrt.ac.lk
description: 'Personal Portfolio'
baseurl: "/Portfolio-Auto" # the subpath of your site, e.g. /blog
url: 
portfolio_url: https://devindesilva.github.io/Portfolio-Auto/personal
cv_url: https://drive.google.com/file/d/1S9l3enfPX48m0KydW-mxPzRbqq0oefp5/view?usp=sharing
repository: DevinDeSilva/Portfolio-Auto
github: https://github.com/DevinDeSilva

header_image: assets/images/devin_professional.jpg

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  appearance_toggle: true # if appearance can be switched by user

google_analytics:
  tracking_id: G-H2K6ZWCRB5

comments: true
disqus: purelog-jekyll

author: John Doe
author_bio: >-
  I'm a ML Engineer at IronOne Technologies, Austin Texas. My current research interests lie in Explainable AI and Zero-shot Learning Domain and currently I am working on fintech domain and utilizing model explanations to provide valuable insights to a major asset management company. By exploiting my theoretical knowledge, I engaged in projects and work spanning aspects of research, including data analysis, formulating an optimization objective, and algorithm design.
author_pic: https://brennanbrown.ca/img/avatar.png
paginate: 4
paginate_path: "/:num/"

markdown: kramdown

sass:
  style: compressed

assets:
  baseurl: /assets

# Exclude from processing.
exclude:
  - ".jekyll-cache"
  - "Gemfile"
  - "Gemfile.lock"
