# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-assets
  
title: John Doe
email: johndoe@example.com
description: 'Personal Portfolio'
baseurl: "/Portfolio-Auto" # the subpath of your site, e.g. /blog
url: 
portfolio_url: https://github.com/johndoe
cv_url: assets/pdf/cv.pdf
repository: nipdep/portfolio
twitter: https://twitter.com/johndoe
github: 

header_image: assets/images/profile_pic3.png

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  appearance_toggle: true # if appearance can be switched by user

google_analytics:
  tracking_id: G-H2K6ZWCRB5

comments: true
disqus: purelog-jekyll

author: John Doe
author_bio: >-
  John Doe is a software engineer and data scientist. He is currently pursuing a Master's degree in Computer Science at the University of Toronto. His research interests include deep learning, computer vision, and natural language processing.
author_pic: https://brennanbrown.ca/img/avatar.png
paginate: 4
paginate_path: "/:num/"

markdown: kramdown

sass:
  style: compressed

assets:
  baseurl: /assets

# Exclude from processing.
exclude:
  - ".jekyll-cache"
  - "Gemfile"
  - "Gemfile.lock"
