plugins:
  - jekyll-assets

# site settings
title: John Doe
subtitle: Portfolio
email: johndoe@example.com
description: 'Experienced web developer with a passion for creating engaging user experiences.'
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/johndoe
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/johndoe
  Twitter: https://twitter.com/johndoe
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

assets:
  baseurl: /assets

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
